### ISSUE TITLE
no difference between convit_base and convit_base_patch models

### ISSUE THREAD

**Issue by carandraug** [vaishnavmohit/Conviformer#2]
The code for the models `convit_base` and `convit_base_patch` appears to be exactly the same. I'm guessing either one of them is redundant or there's an error somewhere?

**Comment by vaishnavmohit** [comment]
`convit_base` takes the model from `VisionTransformerbase` class and `convit_base_patch` from `VisionTransformer` class. The only difference between these two classes is the presence of a convolutional block in the `patch` named model.
